### ISSUE TITLE
clade hangs with parallel builds on Windows

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#86] opened 2019-03-27 05:46 UTC
_msbuild_ has option _/m_ that can speed up builds in several times times. But clade-intercept hangs when this option is specified at the end of builds. It seems that it waits forever for termination of running programs.

The issue is not very important at all.

**Comment by 17451k** [comment] 2019-04-05 12:41
Parallel builds on Windows are not supported right now (see #92). But the issue you described also sometimes appears on sequential builds, albeit it is hard to reliably reproduce. I will try to find the cause and fix it.

**Comment by 17451k** [comment] 2021-01-15 14:00
The issue was caused by the `vctip.exe` telemetry process, that was launched by `cl.exe` in a detached state to report compile errors. Clade waited for all launched processes to finish their execution, which caused hangs that we observed.

Fixed in Clade 3.3

**Closed by 17451k** 2021-01-15 14:00 UTC
Labels: Low, bug
